### ISSUE TITLE
Ошибка, библеотека не поддерживаетсч

### ISSUE THREAD

**Issue by li0ard** [MegaVasiliy007/sdc-api#13]
На Discord.js не работает

**Comment by M1chnt** [comment]
Все работает, скриншот ошибки пожалуйста.

**Comment by EveryDayRains** [comment]
> На Discord.js не работает

Скрин в студию 👍 У меня все хорошо работает

**Comment by yukisnowflake** [comment]
> На Discord.js не работает

В следующий раз хорошо проверяйте найденный баг на проявление. :wink:
