### ISSUE TITLE
bivaet

### ISSUE THREAD

**Issue by XDopi** [MegaVasiliy007/sdc-api#21]
![image](https://user-images.githubusercontent.com/57643140/81434106-506d6c80-916e-11ea-9da7-8faf86f95afc.png)
discord.js 12
![image](https://user-images.githubusercontent.com/57643140/81434138-624f0f80-916e-11ea-9ca1-9ea755e6d7f4.png)

**Comment by yukisnowflake** [comment]
В процессе исправления. Спасибо за помощь. <3

**Comment by yukisnowflake** [comment]
В PR #22 будет пофикшено. Ждём правок от MegaVasiliy007.
