### ISSUE TITLE
Сделать на нормальном япе 

### ISSUE THREAD

**Issue by Pers1koFF** [MegaVasiliy007/sdc-api#24]
предлагаю сделать это на C# или Python

**Comment by Tegnio** [comment]
Чем тебе js не нравится?

**Comment by Terisback** [comment]
@Pers1koFF Напиши сам, тут 3 запроса

**Comment by yukisnowflake** [comment]
> предлагаю сделать это на C# или Python

Возьми и напиши, или тебе кто-то не даёт?
К слову, "Сделать на нормальном япе" прозвучало как хейт к NodeJS, так что не разбрасывайся словами. Все языки по своему хороши.

**Comment by roxxel** [comment]
> предлагаю сделать это на C# или Python

Если тебе так надо это для шарпа то я могу написать, мне это проблем не составит

**Comment by ghost** [comment]
> предлагаю сделать это на C# или Python

 Если я не ошибаюсь какой-та чел делал модуль под пайтон, про сишарп точно не знаю, но зачем там тебе это?

**Comment by Terisback** [comment]
@Pers1koFF Ну, проблемы написать самому нет, закрывай issue

**Comment by Amirust** [comment]
В чем проблема написать свою такую штуку?
Документация по реквестам и по SD.C тебе в руки, делай.
